### PR TITLE
Fix Issuer Validation

### LINKED ISSUE #66: Paseto.Handlers.PasetoPurposeHandler.ValidateIssuer(...) validates audience, not issuer
```cs
protected virtual void ValidateIssuer(PasetoToken token, PasetoTokenValidationParameters validationParameters)
    {
        if (!validationParameters.ValidateIssuer && !string.IsNullOrWhiteSpace(validationParameters.ValidIssuer))
            return;

        if (token.Payload.HasIssuer())
            new EqualValidator(token.Payload, PasetoRegisteredClaimNames.Audience).Validate(validationParameters.ValidIssuer);
			// I think it should be PasetoRegisteredClaimNames.Issuer ?
}
```

### PR DESCRIPTION
**Pull request by lyra95**

### CODE REVIEW

**Comment by lyra95** [comment]
It's my first time contributing to open source, I did not know that I need to fork repo, instead of clone. haha...

**Comment by daviddesmet** [comment]
> It's my first time contributing to open source, I did not know that I need to fork repo, instead of clone. haha...

No worries, we all have been there 😉

**Comment by daviddesmet** [comment]
Closes #66

**Comment by daviddesmet** [comment]
@lyra95 would you also like to add a test to your PR? You just have to commit and push your changes and it will show up here.

**Comment by lyra95** [comment]
Ok

**Comment by lyra95** [comment]
I've added tests.

I wanted to narrow the test target down to the method `ValidateIssuer()`, but I could not because  the method is protected in abstract class. Instead, I've written tests that generate tokens and verify them, which triggers the target method.

**Comment by daviddesmet** [comment]
@lyra95 Thanks for adding the tests, and don’t worry, those are perfectly fine and should be testing the decoding of the token, there are already tests for the equality validator which the Issuer validator uses.

**Comment by lyra95** [comment]
Thanks!

**Pull request merged**
